---
# tasks file for roles/nxos_prepare
- block:
  - name: Enable NXAPI
    nxos_nxapi:
      host: "{{ inventory_hostname }}"
      username: "{{ switch_username }}"
      password: "{{ switch_password }}"
      enabled: true
      write: false
    register: nxapi_status
    notify:
      - Disable NXAPI

  - name: Write config
    nxos_config:
      host: "{{ inventory_hostname }}"
      username: "{{ switch_username }}"
      password: "{{ switch_password }}"
      save: True
    when: backup

  - name: Delete old config backup
    nxos_dir:
      host: "{{ inventory_hostname }}"
      username: "{{ switch_username }}"
      password: "{{ switch_password }}"
      path: "{{ bootflash_conf_file }}"
      state: absent
    when: overwrite_bootflash_config and backup

  - name: Backup running config to local device
    nxos_config:
      host: "{{ inventory_hostname }}"
      username: "{{ switch_username }}"
      password: "{{ switch_password }}"
      backup: True
    when: backup


  # tag entire block
  tags:
    - always
